public enum StateTransitionTask
{
	VISUAL_TRANSITION_START,
	START_RUN,
	CHANGE_LOCATION,
	SHOW_WAKE_UP,
	NPC_RESPAWN,
	SHOP_RESTOCK,
	SHOW_WIN,
	SHOW_LOSE,
	VISUAL_TRANSITION_FINISH,
	LOCK_CURSOR,
	UNLOCK_CURSOR,
	OTHER
}