#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace PlatformCore.Editor
{
	/// <summary>
	/// Генератор статического класса ResourcePaths из структуры папок Resources
	/// </summary>
	public static class ResourcePathsGenerator
	{
		private const string OUTPUT_PATH = "Assets/PlatformCore/Services/Factory/ResourcePaths.cs";
		private const string RESOURCES_FOLDER = "Assets/Resources";

		[MenuItem("Tools/Generate ResourcePaths")]
		public static void Generate()
		{
			if (!Directory.Exists(RESOURCES_FOLDER))
			{
				Debug.LogError($"[ResourcePathsGenerator] Resources folder not found: {RESOURCES_FOLDER}");
				return;
			}

			Debug.Log("[ResourcePathsGenerator] Scanning Resources folder...");

			// Сканируем Resources папку
			var structure = ScanResourcesFolder();

			// Генерируем C# код
			var code = GenerateCode(structure);

			// Создаём директорию если нужно
			var directory = Path.GetDirectoryName(OUTPUT_PATH);
			if (!Directory.Exists(directory))
			{
				Directory.CreateDirectory(directory);
			}

			// Записываем файл
			File.WriteAllText(OUTPUT_PATH, code);

			// Обновляем AssetDatabase
			AssetDatabase.Refresh();

			Debug.Log($"[ResourcePathsGenerator] Generated: {OUTPUT_PATH}");
		}

		private static Dictionary<string, List<string>> ScanResourcesFolder()
		{
			var structure = new Dictionary<string, List<string>>();

			// Получаем все файлы в Resources
			var allFiles = Directory.GetFiles(RESOURCES_FOLDER, "*.*", SearchOption.AllDirectories)
				.Where(f => !f.EndsWith(".meta")) // Игнорируем .meta файлы
				.ToArray();

			foreach (var filePath in allFiles)
			{
				// Конвертируем в относительный путь от Resources
				var relativePath = filePath
					.Replace(RESOURCES_FOLDER + Path.DirectorySeparatorChar, "")
					.Replace(Path.DirectorySeparatorChar, '/');

				// Убираем расширение
				var pathWithoutExtension = Path.ChangeExtension(relativePath, null);

				// Определяем категорию (первая папка)
				var parts = pathWithoutExtension.Split('/');
				var category = parts.Length > 1 ? parts[0] : "Root";
				var resourcePath = pathWithoutExtension;

				// Добавляем в структуру
				if (!structure.ContainsKey(category))
				{
					structure[category] = new List<string>();
				}

				structure[category].Add(resourcePath);
			}

			return structure;
		}

		private static string GenerateCode(Dictionary<string, List<string>> structure)
		{
			var sb = new StringBuilder();

			// Header
			sb.AppendLine("// AUTO-GENERATED FILE");
			sb.AppendLine("// DO NOT EDIT MANUALLY!");
			sb.AppendLine("// Generated by: Tools -> Generate ResourcePaths");
			sb.AppendLine();
			sb.AppendLine("namespace PlatformCore.Services.Factory");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic static class ResourcePaths");
			sb.AppendLine("\t{");

			// Generate nested classes for each category
			foreach (var category in structure.Keys.OrderBy(k => k))
			{
				sb.AppendLine($"\t\tpublic static class {SanitizeClassName(category)}");
				sb.AppendLine("\t\t{");

				foreach (var path in structure[category].OrderBy(p => p))
				{
					var fieldName = GenerateFieldName(path);
					sb.AppendLine($"\t\t\tpublic const string {fieldName} = \"{path}\";");
				}

				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			return sb.ToString();
		}

		private static string SanitizeClassName(string name)
		{
			// Убираем недопустимые символы для имени класса
			var sanitized = new string(name.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());

			// Первый символ должен быть буквой
			if (sanitized.Length > 0 && char.IsDigit(sanitized[0]))
			{
				sanitized = "_" + sanitized;
			}

			return string.IsNullOrEmpty(sanitized) ? "Unknown" : sanitized;
		}

		private static string GenerateFieldName(string path)
		{
			// Берём последнюю часть пути как имя
			var parts = path.Split('/');
			var name = parts[parts.Length - 1];

			// Убираем недопустимые символы
			var sanitized = new string(name.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());

			// Первый символ должен быть буквой
			if (sanitized.Length > 0 && char.IsDigit(sanitized[0]))
			{
				sanitized = "_" + sanitized;
			}

			return string.IsNullOrEmpty(sanitized) ? "Unknown" : sanitized;
		}
	}
}
#endif