// AUTO-GENERATED FILE
// DO NOT EDIT MANUALLY!
// Generated by: Tools -> Generate ResourcePaths

namespace PlatformCore.Services.Factory
{
	public static class ResourcePaths
	{
		public static class Images
		{
			public const string TrainArriving = "Images/TrainArriving";
			public const string TrainLeaving = "Images/TrainLeaving";
		}

		public static class Items
		{
			public const string DicePrefab = "Items/DicePrefab";
		}

		public static class Json
		{
			public const string dice_game_rules = "Json/dice_game_rules";
			public const string dice_types = "Json/dice_types";
			public const string player = "Json/player";
			public const string run_rules = "Json/run_rules";
			public const string shop = "Json/shop";
			public const string texts_eng = "Json/texts_eng";
			public const string texts_ru = "Json/texts_ru";
		}

		public static class Player
		{
			public const string Character = "Player/Character";
			public const string CinemachineCamera = "Player/CinemachineCamera";
			public const string NpcAnim = "Player/NpcAnim";
			public const string NpcBase = "Player/NpcBase";
			public const string NpcConductor = "Player/NpcConductor";
			public const string NpcEnemy = "Player/NpcEnemy";
			public const string NpcPassenger = "Player/NpcPassenger";
			public const string NpcShopKeeper = "Player/NpcShopKeeper";
			public const string PlayerBase = "Player/PlayerBase";
			public const string Sit = "Player/Sit";
			public const string StandUp = "Player/StandUp";
		}

		public static class Root
		{
			public const string DOTweenSettings = "DOTweenSettings";
		}

		public static class Shop
		{
			public const string ShopItemDice = "Shop/ShopItemDice";
			public const string TradeItem = "Shop/TradeItem";
		}

		public static class UI
		{
			public const string UICursorView = "UI/UICursorView";
			public const string UIHintView = "UI/UIHintView";
			public const string UILevelView = "UI/UILevelView";
			public const string UILoseView = "UI/UILoseView";
			public const string UIMainMenu = "UI/UIMainMenu";
			public const string UIPlayerHud = "UI/UIPlayerHud";
			public const string UIQuestsView = "UI/UIQuestsView";
			public const string UISettings = "UI/UISettings";
			public const string UISleepView = "UI/UISleepView";
			public const string UISpeechView = "UI/UISpeechView";
			public const string UITooltip = "UI/UITooltip";
			public const string UIWinView = "UI/UIWinView";
		}

	}
}
