// AUTO-GENERATED FILE
// DO NOT EDIT MANUALLY!
// Generated by: Tools -> Generate ResourcePaths

namespace PlatformCore.Services.Factory
{
	public static class ResourcePaths
	{
		public static class Items
		{
			public const string DicePrefab = "Items/DicePrefab";
		}

		public static class Player
		{
			public const string CinemachineCamera = "Player/CinemachineCamera";
			public const string PlayerPrefab = "Player/PlayerPrefab";
		}

		public static class Root
		{
			public const string DOTweenSettings = "DOTweenSettings";
		}

		public static class UI
		{
			public const string UIMainMenu = "UI/UIMainMenu";
			public const string UISettings = "UI/UISettings";
		}

	}
}
